let age = 25;
console.log(age);
let name = "Іван";
console.log(name);
let isStudent = true;
console.log(isStudent);
let myString = "Великі справи починаються з малого.";
console.log(myString);
let myNumber = 15;
myNumber += 10;
console.log(myNumber);
let myNull = null;
console.log(myNull);
let userName = prompt("Введіть своє ім’я");
alert("Ваше ім’я: " + userName);
console.log(typeof userName);
let userAnswer = confirm("Ви дійсно хочете покинути сторінку?");
console.log("Відповідь користувача: ", userAnswer);
alert("Увага! Дія може бути небезпечною.");
let confirmAction = confirm("Ви впевнені, що хочете продовжити?");
console.log("Користувач підтвердив дію: ", confirmAction);
